#!/data/data/com.termux/files/usr/bin/sh

# There needs to be a folder at $ANDROID_DATA/dalvik-cache
export ANDROID_DATA=/data/data/com.termux/files/usr/var/android/
mkdir -p $ANDROID_DATA/dalvik-cache

if [ -x /apex/com.android.art/bin/dalvikvm ]; then
	DALVIKVM="/apex/com.android.art/bin/dalvikvm"
else
	DALVIKVM="/system/bin/dalvikvm"
fi

unset LD_LIBRARY_PATH LD_PRELOAD
exec "$DALVIKVM" -Xusejit:true -Xnoimage-dex2oat -Djava.io.tmpdir=/data/data/com.termux/files/usr/tmp "$@"
