[[queries]]
name = "firefox-release-crashrate"
package = "org.mozilla.firefox"
metric_set = "crashrate"
days = 1
top = 10
resolve_versions = true
compare_days = 28

[[queries]]
name = "firefox-release-anrrate"
package = "org.mozilla.firefox"
metric_set = "anrrate"
days = 1
top = 10
resolve_versions = true
compare_days = 28

[[queries]]
name = "firefox-release-lmkrate"
package = "org.mozilla.firefox"
metric_set = "lmkrate"
days = 1
top = 10
resolve_versions = true
compare_days = 28

[[queries]]
name = "firefox-beta-crashrate"
package = "org.mozilla.firefox_beta"
metric_set = "crashrate"
days = 1
top = 10
resolve_versions = true
compare_days = 28

[[queries]]
name = "firefox-beta-anrrate"
package = "org.mozilla.firefox_beta"
metric_set = "anrrate"
days = 1
top = 10
resolve_versions = true
compare_days = 28

[[queries]]
name = "firefox-beta-lmkrate"
package = "org.mozilla.firefox_beta"
metric_set = "lmkrate"
days = 1
top = 10
resolve_versions = true
compare_days = 28

[[queries]]
name = "firefox-nightly-crashrate"
package = "org.mozilla.fenix"
metric_set = "crashrate"
days = 1
top = 10
resolve_versions = true
compare_days = 28

[[queries]]
name = "firefox-nightly-anrrate"
package = "org.mozilla.fenix"
metric_set = "anrrate"
days = 1
top = 10
resolve_versions = true
compare_days = 28

[[queries]]
name = "firefox-nightly-lmkrate"
package = "org.mozilla.fenix"
metric_set = "lmkrate"
days = 1
top = 10
resolve_versions = true
compare_days = 28

[[queries]]
name = "focus-crashrate"
package = "org.mozilla.focus"
metric_set = "crashrate"
days = 1
top = 10
sort_by = "distinctUsers"
compare_days = 28

[[queries]]
name = "focus-anrrate"
package = "org.mozilla.focus"
metric_set = "anrrate"
days = 1
top = 10
sort_by = "distinctUsers"
compare_days = 28

[[queries]]
name = "focus-lmkrate"
package = "org.mozilla.focus"
metric_set = "lmkrate"
days = 1
top = 10
sort_by = "distinctUsers"
compare_days = 28

[[queries]]
name = "firefox-release-anomalies"
package = "org.mozilla.firefox"
anomalies = true
days = 7

[[queries]]
name = "firefox-beta-anomalies"
package = "org.mozilla.firefox_beta"
anomalies = true
days = 7

[[queries]]
name = "firefox-nightly-anomalies"
package = "org.mozilla.fenix"
anomalies = true
days = 7

[[queries]]
name = "focus-anomalies"
package = "org.mozilla.focus"
anomalies = true
days = 7